// <auto-generated />
namespace Hubo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class dayshift2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dayshift2));
        
        string IMigrationMetadata.Id
        {
            get { return "201706192238121_dayshift2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
